name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Run lint
      run: make lint MAKE_LINT_ERROR_OUT=1

    - name: Run tests
      run: make test
